#ifndef CODES_H
#define CODES_H

enum M_Code
{
    M_CODE_CONNECT = 0,
    M_CODE_WATER,
    M_CODE_HEATER,
    M_CODE_DONE
};

enum CP_Code
{
    CP_CODE_CONNECT = 0,
    CP_CODE_CONSOLE,
    CP_CODE_TOTALWATER,
    CP_CODE_TOTALPOWER,
    CP_CODE_GETCLIENTS,
    CP_CODE_SETCLIENT,
    CP_CODE_DISABLEALLCLIENTS
};

#endif